// automatically generated by the FlatBuffers compiler, do not modify

package scpack;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class T_OFFLINE_MSG extends Table {
  public static T_OFFLINE_MSG getRootAsT_OFFLINE_MSG(ByteBuffer _bb) { return getRootAsT_OFFLINE_MSG(_bb, new T_OFFLINE_MSG()); }
  public static T_OFFLINE_MSG getRootAsT_OFFLINE_MSG(ByteBuffer _bb, T_OFFLINE_MSG obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public T_OFFLINE_MSG __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public long opUserId() { int o = __offset(4); return o != 0 ? bb.getLong(o + bb_pos) : 0; }
  public long messageId() { int o = __offset(6); return o != 0 ? bb.getLong(o + bb_pos) : 0; }
  public commonpack.S_MSG sMsg() { return sMsg(new commonpack.S_MSG()); }
  public commonpack.S_MSG sMsg(commonpack.S_MSG obj) { int o = __offset(8); return o != 0 ? obj.__init(__indirect(o + bb_pos), bb) : null; }
  public long bId() { int o = __offset(10); return o != 0 ? bb.getLong(o + bb_pos) : 0; }
  public long wId() { int o = __offset(12); return o != 0 ? bb.getLong(o + bb_pos) : 0; }
  public long cId() { int o = __offset(14); return o != 0 ? bb.getLong(o + bb_pos) : 0; }

  public static int createT_OFFLINE_MSG(FlatBufferBuilder builder,
      long op_user_id,
      long message_id,
      int s_msgOffset,
      long b_id,
      long w_id,
      long c_id) {
    builder.startObject(6);
    T_OFFLINE_MSG.addCId(builder, c_id);
    T_OFFLINE_MSG.addWId(builder, w_id);
    T_OFFLINE_MSG.addBId(builder, b_id);
    T_OFFLINE_MSG.addMessageId(builder, message_id);
    T_OFFLINE_MSG.addOpUserId(builder, op_user_id);
    T_OFFLINE_MSG.addSMsg(builder, s_msgOffset);
    return T_OFFLINE_MSG.endT_OFFLINE_MSG(builder);
  }

  public static void startT_OFFLINE_MSG(FlatBufferBuilder builder) { builder.startObject(6); }
  public static void addOpUserId(FlatBufferBuilder builder, long opUserId) { builder.addLong(0, opUserId, 0); }
  public static void addMessageId(FlatBufferBuilder builder, long messageId) { builder.addLong(1, messageId, 0); }
  public static void addSMsg(FlatBufferBuilder builder, int sMsgOffset) { builder.addOffset(2, sMsgOffset, 0); }
  public static void addBId(FlatBufferBuilder builder, long bId) { builder.addLong(3, bId, 0); }
  public static void addWId(FlatBufferBuilder builder, long wId) { builder.addLong(4, wId, 0); }
  public static void addCId(FlatBufferBuilder builder, long cId) { builder.addLong(5, cId, 0); }
  public static int endT_OFFLINE_MSG(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
  public static void finishT_OFFLINE_MSGBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
}

