// automatically generated by the FlatBuffers compiler, do not modify

package scpack;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class T_SINGLE_CHAT_STATUS_RQ extends Table {
  public static T_SINGLE_CHAT_STATUS_RQ getRootAsT_SINGLE_CHAT_STATUS_RQ(ByteBuffer _bb) { return getRootAsT_SINGLE_CHAT_STATUS_RQ(_bb, new T_SINGLE_CHAT_STATUS_RQ()); }
  public static T_SINGLE_CHAT_STATUS_RQ getRootAsT_SINGLE_CHAT_STATUS_RQ(ByteBuffer _bb, T_SINGLE_CHAT_STATUS_RQ obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public T_SINGLE_CHAT_STATUS_RQ __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public commonpack.S_RQ_HEAD sRqHead() { return sRqHead(new commonpack.S_RQ_HEAD()); }
  public commonpack.S_RQ_HEAD sRqHead(commonpack.S_RQ_HEAD obj) { int o = __offset(4); return o != 0 ? obj.__init(o + bb_pos, bb) : null; }
  public long opUserId() { int o = __offset(6); return o != 0 ? bb.getLong(o + bb_pos) : 0; }
  public byte chatStatus() { int o = __offset(8); return o != 0 ? bb.get(o + bb_pos) : 0; }

  public static void startT_SINGLE_CHAT_STATUS_RQ(FlatBufferBuilder builder) { builder.startObject(3); }
  public static void addSRqHead(FlatBufferBuilder builder, int sRqHeadOffset) { builder.addStruct(0, sRqHeadOffset, 0); }
  public static void addOpUserId(FlatBufferBuilder builder, long opUserId) { builder.addLong(1, opUserId, 0); }
  public static void addChatStatus(FlatBufferBuilder builder, byte chatStatus) { builder.addByte(2, chatStatus, 0); }
  public static int endT_SINGLE_CHAT_STATUS_RQ(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
  public static void finishT_SINGLE_CHAT_STATUS_RQBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
}

