// automatically generated by the FlatBuffers compiler, do not modify

package userpack;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class T_GET_ME_INFO_RQ extends Table {
  public static T_GET_ME_INFO_RQ getRootAsT_GET_ME_INFO_RQ(ByteBuffer _bb) { return getRootAsT_GET_ME_INFO_RQ(_bb, new T_GET_ME_INFO_RQ()); }
  public static T_GET_ME_INFO_RQ getRootAsT_GET_ME_INFO_RQ(ByteBuffer _bb, T_GET_ME_INFO_RQ obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public T_GET_ME_INFO_RQ __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public commonpack.S_RQ_HEAD sRqHead() { return sRqHead(new commonpack.S_RQ_HEAD()); }
  public commonpack.S_RQ_HEAD sRqHead(commonpack.S_RQ_HEAD obj) { int o = __offset(4); return o != 0 ? obj.__init(o + bb_pos, bb) : null; }
  public String token() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer tokenAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }

  public static void startT_GET_ME_INFO_RQ(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addSRqHead(FlatBufferBuilder builder, int sRqHeadOffset) { builder.addStruct(0, sRqHeadOffset, 0); }
  public static void addToken(FlatBufferBuilder builder, int tokenOffset) { builder.addOffset(1, tokenOffset, 0); }
  public static int endT_GET_ME_INFO_RQ(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
  public static void finishT_GET_ME_INFO_RQBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
}

