// automatically generated by the FlatBuffers compiler, do not modify

package userpack;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class T_GET_USERINFO extends Table {
  public static T_GET_USERINFO getRootAsT_GET_USERINFO(ByteBuffer _bb) { return getRootAsT_GET_USERINFO(_bb, new T_GET_USERINFO()); }
  public static T_GET_USERINFO getRootAsT_GET_USERINFO(ByteBuffer _bb, T_GET_USERINFO obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public T_GET_USERINFO __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public long userId() { int o = __offset(4); return o != 0 ? bb.getLong(o + bb_pos) : 0; }
  public String userName() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer userNameAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public String nickName() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer nickNameAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }
  public long mobile() { int o = __offset(10); return o != 0 ? bb.getLong(o + bb_pos) : 0; }

  public static int createT_GET_USERINFO(FlatBufferBuilder builder,
      long user_id,
      int user_nameOffset,
      int nick_nameOffset,
      long mobile) {
    builder.startObject(4);
    T_GET_USERINFO.addMobile(builder, mobile);
    T_GET_USERINFO.addUserId(builder, user_id);
    T_GET_USERINFO.addNickName(builder, nick_nameOffset);
    T_GET_USERINFO.addUserName(builder, user_nameOffset);
    return T_GET_USERINFO.endT_GET_USERINFO(builder);
  }

  public static void startT_GET_USERINFO(FlatBufferBuilder builder) { builder.startObject(4); }
  public static void addUserId(FlatBufferBuilder builder, long userId) { builder.addLong(0, userId, 0); }
  public static void addUserName(FlatBufferBuilder builder, int userNameOffset) { builder.addOffset(1, userNameOffset, 0); }
  public static void addNickName(FlatBufferBuilder builder, int nickNameOffset) { builder.addOffset(2, nickNameOffset, 0); }
  public static void addMobile(FlatBufferBuilder builder, long mobile) { builder.addLong(3, mobile, 0); }
  public static int endT_GET_USERINFO(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

