// automatically generated by the FlatBuffers compiler, do not modify

package userpack;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class T_GET_USERLST_INFO_RQ extends Table {
  public static T_GET_USERLST_INFO_RQ getRootAsT_GET_USERLST_INFO_RQ(ByteBuffer _bb) { return getRootAsT_GET_USERLST_INFO_RQ(_bb, new T_GET_USERLST_INFO_RQ()); }
  public static T_GET_USERLST_INFO_RQ getRootAsT_GET_USERLST_INFO_RQ(ByteBuffer _bb, T_GET_USERLST_INFO_RQ obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public T_GET_USERLST_INFO_RQ __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public commonpack.S_RQ_HEAD sRqHead() { return sRqHead(new commonpack.S_RQ_HEAD()); }
  public commonpack.S_RQ_HEAD sRqHead(commonpack.S_RQ_HEAD obj) { int o = __offset(4); return o != 0 ? obj.__init(o + bb_pos, bb) : null; }
  public long userLst(int j) { int o = __offset(6); return o != 0 ? bb.getLong(__vector(o) + j * 8) : 0; }
  public int userLstLength() { int o = __offset(6); return o != 0 ? __vector_len(o) : 0; }
  public ByteBuffer userLstAsByteBuffer() { return __vector_as_bytebuffer(6, 8); }
  public long mobileLst(int j) { int o = __offset(8); return o != 0 ? bb.getLong(__vector(o) + j * 8) : 0; }
  public int mobileLstLength() { int o = __offset(8); return o != 0 ? __vector_len(o) : 0; }
  public ByteBuffer mobileLstAsByteBuffer() { return __vector_as_bytebuffer(8, 8); }

  public static void startT_GET_USERLST_INFO_RQ(FlatBufferBuilder builder) { builder.startObject(3); }
  public static void addSRqHead(FlatBufferBuilder builder, int sRqHeadOffset) { builder.addStruct(0, sRqHeadOffset, 0); }
  public static void addUserLst(FlatBufferBuilder builder, int userLstOffset) { builder.addOffset(1, userLstOffset, 0); }
  public static int createUserLstVector(FlatBufferBuilder builder, long[] data) { builder.startVector(8, data.length, 8); for (int i = data.length - 1; i >= 0; i--) builder.addLong(data[i]); return builder.endVector(); }
  public static void startUserLstVector(FlatBufferBuilder builder, int numElems) { builder.startVector(8, numElems, 8); }
  public static void addMobileLst(FlatBufferBuilder builder, int mobileLstOffset) { builder.addOffset(2, mobileLstOffset, 0); }
  public static int createMobileLstVector(FlatBufferBuilder builder, long[] data) { builder.startVector(8, data.length, 8); for (int i = data.length - 1; i >= 0; i--) builder.addLong(data[i]); return builder.endVector(); }
  public static void startMobileLstVector(FlatBufferBuilder builder, int numElems) { builder.startVector(8, numElems, 8); }
  public static int endT_GET_USERLST_INFO_RQ(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
  public static void finishT_GET_USERLST_INFO_RQBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
}

