// automatically generated by the FlatBuffers compiler, do not modify

package userpack;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class T_GET_ME_INFO_RS extends Table {
  public static T_GET_ME_INFO_RS getRootAsT_GET_ME_INFO_RS(ByteBuffer _bb) { return getRootAsT_GET_ME_INFO_RS(_bb, new T_GET_ME_INFO_RS()); }
  public static T_GET_ME_INFO_RS getRootAsT_GET_ME_INFO_RS(ByteBuffer _bb, T_GET_ME_INFO_RS obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public T_GET_ME_INFO_RS __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public commonpack.S_RS_HEAD sRsHead() { return sRsHead(new commonpack.S_RS_HEAD()); }
  public commonpack.S_RS_HEAD sRsHead(commonpack.S_RS_HEAD obj) { int o = __offset(4); return o != 0 ? obj.__init(o + bb_pos, bb) : null; }
  public String token() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer tokenAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public String verification() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer verificationAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }
  public long userId() { int o = __offset(10); return o != 0 ? bb.getLong(o + bb_pos) : 0; }
  public String userName() { int o = __offset(12); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer userNameAsByteBuffer() { return __vector_as_bytebuffer(12, 1); }
  public long birthday() { int o = __offset(14); return o != 0 ? bb.getLong(o + bb_pos) : 0; }
  public String city() { int o = __offset(16); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer cityAsByteBuffer() { return __vector_as_bytebuffer(16, 1); }
  public String province() { int o = __offset(18); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer provinceAsByteBuffer() { return __vector_as_bytebuffer(18, 1); }
  public String signature() { int o = __offset(20); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer signatureAsByteBuffer() { return __vector_as_bytebuffer(20, 1); }
  public long mobile() { int o = __offset(22); return o != 0 ? bb.getLong(o + bb_pos) : 0; }
  public String nickName() { int o = __offset(24); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer nickNameAsByteBuffer() { return __vector_as_bytebuffer(24, 1); }
  public byte sex() { int o = __offset(26); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public String mail() { int o = __offset(28); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer mailAsByteBuffer() { return __vector_as_bytebuffer(28, 1); }

  public static void startT_GET_ME_INFO_RS(FlatBufferBuilder builder) { builder.startObject(13); }
  public static void addSRsHead(FlatBufferBuilder builder, int sRsHeadOffset) { builder.addStruct(0, sRsHeadOffset, 0); }
  public static void addToken(FlatBufferBuilder builder, int tokenOffset) { builder.addOffset(1, tokenOffset, 0); }
  public static void addVerification(FlatBufferBuilder builder, int verificationOffset) { builder.addOffset(2, verificationOffset, 0); }
  public static void addUserId(FlatBufferBuilder builder, long userId) { builder.addLong(3, userId, 0); }
  public static void addUserName(FlatBufferBuilder builder, int userNameOffset) { builder.addOffset(4, userNameOffset, 0); }
  public static void addBirthday(FlatBufferBuilder builder, long birthday) { builder.addLong(5, birthday, 0); }
  public static void addCity(FlatBufferBuilder builder, int cityOffset) { builder.addOffset(6, cityOffset, 0); }
  public static void addProvince(FlatBufferBuilder builder, int provinceOffset) { builder.addOffset(7, provinceOffset, 0); }
  public static void addSignature(FlatBufferBuilder builder, int signatureOffset) { builder.addOffset(8, signatureOffset, 0); }
  public static void addMobile(FlatBufferBuilder builder, long mobile) { builder.addLong(9, mobile, 0); }
  public static void addNickName(FlatBufferBuilder builder, int nickNameOffset) { builder.addOffset(10, nickNameOffset, 0); }
  public static void addSex(FlatBufferBuilder builder, byte sex) { builder.addByte(11, sex, 0); }
  public static void addMail(FlatBufferBuilder builder, int mailOffset) { builder.addOffset(12, mailOffset, 0); }
  public static int endT_GET_ME_INFO_RS(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
  public static void finishT_GET_ME_INFO_RSBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
}

