// automatically generated by the FlatBuffers compiler, do not modify

package userpack;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class T_GET_USER_INFO_RS extends Table {
  public static T_GET_USER_INFO_RS getRootAsT_GET_USER_INFO_RS(ByteBuffer _bb) { return getRootAsT_GET_USER_INFO_RS(_bb, new T_GET_USER_INFO_RS()); }
  public static T_GET_USER_INFO_RS getRootAsT_GET_USER_INFO_RS(ByteBuffer _bb, T_GET_USER_INFO_RS obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public T_GET_USER_INFO_RS __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public commonpack.S_RS_HEAD sRsHead() { return sRsHead(new commonpack.S_RS_HEAD()); }
  public commonpack.S_RS_HEAD sRsHead(commonpack.S_RS_HEAD obj) { int o = __offset(4); return o != 0 ? obj.__init(o + bb_pos, bb) : null; }
  public String userMsg() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer userMsgAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public long userId() { int o = __offset(8); return o != 0 ? bb.getLong(o + bb_pos) : 0; }
  public String userName() { int o = __offset(10); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer userNameAsByteBuffer() { return __vector_as_bytebuffer(10, 1); }
  public long birthday() { int o = __offset(12); return o != 0 ? bb.getLong(o + bb_pos) : 0; }
  public String city() { int o = __offset(14); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer cityAsByteBuffer() { return __vector_as_bytebuffer(14, 1); }
  public String province() { int o = __offset(16); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer provinceAsByteBuffer() { return __vector_as_bytebuffer(16, 1); }
  public String signature() { int o = __offset(18); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer signatureAsByteBuffer() { return __vector_as_bytebuffer(18, 1); }
  public long mobile() { int o = __offset(20); return o != 0 ? bb.getLong(o + bb_pos) : 0; }
  public String nickName() { int o = __offset(22); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer nickNameAsByteBuffer() { return __vector_as_bytebuffer(22, 1); }
  public byte sex() { int o = __offset(24); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public String mail() { int o = __offset(26); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer mailAsByteBuffer() { return __vector_as_bytebuffer(26, 1); }

  public static void startT_GET_USER_INFO_RS(FlatBufferBuilder builder) { builder.startObject(12); }
  public static void addSRsHead(FlatBufferBuilder builder, int sRsHeadOffset) { builder.addStruct(0, sRsHeadOffset, 0); }
  public static void addUserMsg(FlatBufferBuilder builder, int userMsgOffset) { builder.addOffset(1, userMsgOffset, 0); }
  public static void addUserId(FlatBufferBuilder builder, long userId) { builder.addLong(2, userId, 0); }
  public static void addUserName(FlatBufferBuilder builder, int userNameOffset) { builder.addOffset(3, userNameOffset, 0); }
  public static void addBirthday(FlatBufferBuilder builder, long birthday) { builder.addLong(4, birthday, 0); }
  public static void addCity(FlatBufferBuilder builder, int cityOffset) { builder.addOffset(5, cityOffset, 0); }
  public static void addProvince(FlatBufferBuilder builder, int provinceOffset) { builder.addOffset(6, provinceOffset, 0); }
  public static void addSignature(FlatBufferBuilder builder, int signatureOffset) { builder.addOffset(7, signatureOffset, 0); }
  public static void addMobile(FlatBufferBuilder builder, long mobile) { builder.addLong(8, mobile, 0); }
  public static void addNickName(FlatBufferBuilder builder, int nickNameOffset) { builder.addOffset(9, nickNameOffset, 0); }
  public static void addSex(FlatBufferBuilder builder, byte sex) { builder.addByte(10, sex, 0); }
  public static void addMail(FlatBufferBuilder builder, int mailOffset) { builder.addOffset(11, mailOffset, 0); }
  public static int endT_GET_USER_INFO_RS(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
  public static void finishT_GET_USER_INFO_RSBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
}

