// automatically generated by the FlatBuffers compiler, do not modify

package userpack;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class T_GET_USERLST_INFO_RS extends Table {
  public static T_GET_USERLST_INFO_RS getRootAsT_GET_USERLST_INFO_RS(ByteBuffer _bb) { return getRootAsT_GET_USERLST_INFO_RS(_bb, new T_GET_USERLST_INFO_RS()); }
  public static T_GET_USERLST_INFO_RS getRootAsT_GET_USERLST_INFO_RS(ByteBuffer _bb, T_GET_USERLST_INFO_RS obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public T_GET_USERLST_INFO_RS __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public commonpack.S_RS_HEAD sRsHead() { return sRsHead(new commonpack.S_RS_HEAD()); }
  public commonpack.S_RS_HEAD sRsHead(commonpack.S_RS_HEAD obj) { int o = __offset(4); return o != 0 ? obj.__init(o + bb_pos, bb) : null; }
  public T_GET_USERINFO userLstInfo(int j) { return userLstInfo(new T_GET_USERINFO(), j); }
  public T_GET_USERINFO userLstInfo(T_GET_USERINFO obj, int j) { int o = __offset(6); return o != 0 ? obj.__init(__indirect(__vector(o) + j * 4), bb) : null; }
  public int userLstInfoLength() { int o = __offset(6); return o != 0 ? __vector_len(o) : 0; }
  public long userNoLst(int j) { int o = __offset(8); return o != 0 ? bb.getLong(__vector(o) + j * 8) : 0; }
  public int userNoLstLength() { int o = __offset(8); return o != 0 ? __vector_len(o) : 0; }
  public ByteBuffer userNoLstAsByteBuffer() { return __vector_as_bytebuffer(8, 8); }

  public static void startT_GET_USERLST_INFO_RS(FlatBufferBuilder builder) { builder.startObject(3); }
  public static void addSRsHead(FlatBufferBuilder builder, int sRsHeadOffset) { builder.addStruct(0, sRsHeadOffset, 0); }
  public static void addUserLstInfo(FlatBufferBuilder builder, int userLstInfoOffset) { builder.addOffset(1, userLstInfoOffset, 0); }
  public static int createUserLstInfoVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startUserLstInfoVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addUserNoLst(FlatBufferBuilder builder, int userNoLstOffset) { builder.addOffset(2, userNoLstOffset, 0); }
  public static int createUserNoLstVector(FlatBufferBuilder builder, long[] data) { builder.startVector(8, data.length, 8); for (int i = data.length - 1; i >= 0; i--) builder.addLong(data[i]); return builder.endVector(); }
  public static void startUserNoLstVector(FlatBufferBuilder builder, int numElems) { builder.startVector(8, numElems, 8); }
  public static int endT_GET_USERLST_INFO_RS(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
  public static void finishT_GET_USERLST_INFO_RSBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
}

