// automatically generated by the FlatBuffers compiler, do not modify

package userpack;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class T_REGISTER_APNS_RS extends Table {
  public static T_REGISTER_APNS_RS getRootAsT_REGISTER_APNS_RS(ByteBuffer _bb) { return getRootAsT_REGISTER_APNS_RS(_bb, new T_REGISTER_APNS_RS()); }
  public static T_REGISTER_APNS_RS getRootAsT_REGISTER_APNS_RS(ByteBuffer _bb, T_REGISTER_APNS_RS obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public T_REGISTER_APNS_RS __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public commonpack.S_RS_HEAD sRsHead() { return sRsHead(new commonpack.S_RS_HEAD()); }
  public commonpack.S_RS_HEAD sRsHead(commonpack.S_RS_HEAD obj) { int o = __offset(4); return o != 0 ? obj.__init(o + bb_pos, bb) : null; }
  public String deviceToken() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer deviceTokenAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }

  public static void startT_REGISTER_APNS_RS(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addSRsHead(FlatBufferBuilder builder, int sRsHeadOffset) { builder.addStruct(0, sRsHeadOffset, 0); }
  public static void addDeviceToken(FlatBufferBuilder builder, int deviceTokenOffset) { builder.addOffset(1, deviceTokenOffset, 0); }
  public static int endT_REGISTER_APNS_RS(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
  public static void finishT_REGISTER_APNS_RSBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
}

