// automatically generated by the FlatBuffers compiler, do not modify

package userpack;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class T_USER_COMPLAINT_RS extends Table {
  public static T_USER_COMPLAINT_RS getRootAsT_USER_COMPLAINT_RS(ByteBuffer _bb) { return getRootAsT_USER_COMPLAINT_RS(_bb, new T_USER_COMPLAINT_RS()); }
  public static T_USER_COMPLAINT_RS getRootAsT_USER_COMPLAINT_RS(ByteBuffer _bb, T_USER_COMPLAINT_RS obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public T_USER_COMPLAINT_RS __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public commonpack.S_RS_HEAD sRsHead() { return sRsHead(new commonpack.S_RS_HEAD()); }
  public commonpack.S_RS_HEAD sRsHead(commonpack.S_RS_HEAD obj) { int o = __offset(4); return o != 0 ? obj.__init(o + bb_pos, bb) : null; }
  public long userId() { int o = __offset(6); return o != 0 ? bb.getLong(o + bb_pos) : 0; }
  public byte type() { int o = __offset(8); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public String reason() { int o = __offset(10); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer reasonAsByteBuffer() { return __vector_as_bytebuffer(10, 1); }

  public static void startT_USER_COMPLAINT_RS(FlatBufferBuilder builder) { builder.startObject(4); }
  public static void addSRsHead(FlatBufferBuilder builder, int sRsHeadOffset) { builder.addStruct(0, sRsHeadOffset, 0); }
  public static void addUserId(FlatBufferBuilder builder, long userId) { builder.addLong(1, userId, 0); }
  public static void addType(FlatBufferBuilder builder, byte type) { builder.addByte(2, type, 0); }
  public static void addReason(FlatBufferBuilder builder, int reasonOffset) { builder.addOffset(3, reasonOffset, 0); }
  public static int endT_USER_COMPLAINT_RS(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
  public static void finishT_USER_COMPLAINT_RSBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
}

