// automatically generated by the FlatBuffers compiler, do not modify

package syspack;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class T_LOGIN_RS extends Table {
  public static T_LOGIN_RS getRootAsT_LOGIN_RS(ByteBuffer _bb) { return getRootAsT_LOGIN_RS(_bb, new T_LOGIN_RS()); }
  public static T_LOGIN_RS getRootAsT_LOGIN_RS(ByteBuffer _bb, T_LOGIN_RS obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public T_LOGIN_RS __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public commonpack.S_RS_HEAD sRsHead() { return sRsHead(new commonpack.S_RS_HEAD()); }
  public commonpack.S_RS_HEAD sRsHead(commonpack.S_RS_HEAD obj) { int o = __offset(4); return o != 0 ? obj.__init(o + bb_pos, bb) : null; }
  public long serverTime() { int o = __offset(6); return o != 0 ? bb.getLong(o + bb_pos) : 0; }

  public static void startT_LOGIN_RS(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addSRsHead(FlatBufferBuilder builder, int sRsHeadOffset) { builder.addStruct(0, sRsHeadOffset, 0); }
  public static void addServerTime(FlatBufferBuilder builder, long serverTime) { builder.addLong(1, serverTime, 0); }
  public static int endT_LOGIN_RS(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
  public static void finishT_LOGIN_RSBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
}

