// automatically generated by the FlatBuffers compiler, do not modify

package offcialpack;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class T_CLIENT_OFFCIAL_SEND_MESSAGE_RS extends Table {
  public static T_CLIENT_OFFCIAL_SEND_MESSAGE_RS getRootAsT_CLIENT_OFFCIAL_SEND_MESSAGE_RS(ByteBuffer _bb) { return getRootAsT_CLIENT_OFFCIAL_SEND_MESSAGE_RS(_bb, new T_CLIENT_OFFCIAL_SEND_MESSAGE_RS()); }
  public static T_CLIENT_OFFCIAL_SEND_MESSAGE_RS getRootAsT_CLIENT_OFFCIAL_SEND_MESSAGE_RS(ByteBuffer _bb, T_CLIENT_OFFCIAL_SEND_MESSAGE_RS obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public T_CLIENT_OFFCIAL_SEND_MESSAGE_RS __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public commonpack.S_RS_HEAD sRsHead() { return sRsHead(new commonpack.S_RS_HEAD()); }
  public commonpack.S_RS_HEAD sRsHead(commonpack.S_RS_HEAD obj) { int o = __offset(4); return o != 0 ? obj.__init(o + bb_pos, bb) : null; }
  public long messageId() { int o = __offset(6); return o != 0 ? bb.getLong(o + bb_pos) : 0; }
  public long offcialId() { int o = __offset(8); return o != 0 ? bb.getLong(o + bb_pos) : 0; }
  public long toUserLst(int j) { int o = __offset(10); return o != 0 ? bb.getLong(__vector(o) + j * 8) : 0; }
  public int toUserLstLength() { int o = __offset(10); return o != 0 ? __vector_len(o) : 0; }
  public ByteBuffer toUserLstAsByteBuffer() { return __vector_as_bytebuffer(10, 8); }
  public commonpack.S_MSG sMsg() { return sMsg(new commonpack.S_MSG()); }
  public commonpack.S_MSG sMsg(commonpack.S_MSG obj) { int o = __offset(12); return o != 0 ? obj.__init(__indirect(o + bb_pos), bb) : null; }

  public static void startT_CLIENT_OFFCIAL_SEND_MESSAGE_RS(FlatBufferBuilder builder) { builder.startObject(5); }
  public static void addSRsHead(FlatBufferBuilder builder, int sRsHeadOffset) { builder.addStruct(0, sRsHeadOffset, 0); }
  public static void addMessageId(FlatBufferBuilder builder, long messageId) { builder.addLong(1, messageId, 0); }
  public static void addOffcialId(FlatBufferBuilder builder, long offcialId) { builder.addLong(2, offcialId, 0); }
  public static void addToUserLst(FlatBufferBuilder builder, int toUserLstOffset) { builder.addOffset(3, toUserLstOffset, 0); }
  public static int createToUserLstVector(FlatBufferBuilder builder, long[] data) { builder.startVector(8, data.length, 8); for (int i = data.length - 1; i >= 0; i--) builder.addLong(data[i]); return builder.endVector(); }
  public static void startToUserLstVector(FlatBufferBuilder builder, int numElems) { builder.startVector(8, numElems, 8); }
  public static void addSMsg(FlatBufferBuilder builder, int sMsgOffset) { builder.addOffset(4, sMsgOffset, 0); }
  public static int endT_CLIENT_OFFCIAL_SEND_MESSAGE_RS(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
  public static void finishT_CLIENT_OFFCIAL_SEND_MESSAGE_RSBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
}

