// automatically generated by the FlatBuffers compiler, do not modify

package offcialpack;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class T_CLIENT_FANS_GET_OFFLINE_MESSAGE_RQ extends Table {
  public static T_CLIENT_FANS_GET_OFFLINE_MESSAGE_RQ getRootAsT_CLIENT_FANS_GET_OFFLINE_MESSAGE_RQ(ByteBuffer _bb) { return getRootAsT_CLIENT_FANS_GET_OFFLINE_MESSAGE_RQ(_bb, new T_CLIENT_FANS_GET_OFFLINE_MESSAGE_RQ()); }
  public static T_CLIENT_FANS_GET_OFFLINE_MESSAGE_RQ getRootAsT_CLIENT_FANS_GET_OFFLINE_MESSAGE_RQ(ByteBuffer _bb, T_CLIENT_FANS_GET_OFFLINE_MESSAGE_RQ obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public T_CLIENT_FANS_GET_OFFLINE_MESSAGE_RQ __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public commonpack.S_RQ_HEAD sRqHead() { return sRqHead(new commonpack.S_RQ_HEAD()); }
  public commonpack.S_RQ_HEAD sRqHead(commonpack.S_RQ_HEAD obj) { int o = __offset(4); return o != 0 ? obj.__init(o + bb_pos, bb) : null; }
  public T_OFFCIAL_BASE_REQUEST listOffcialOfflineMsgRequest(int j) { return listOffcialOfflineMsgRequest(new T_OFFCIAL_BASE_REQUEST(), j); }
  public T_OFFCIAL_BASE_REQUEST listOffcialOfflineMsgRequest(T_OFFCIAL_BASE_REQUEST obj, int j) { int o = __offset(6); return o != 0 ? obj.__init(__indirect(__vector(o) + j * 4), bb) : null; }
  public int listOffcialOfflineMsgRequestLength() { int o = __offset(6); return o != 0 ? __vector_len(o) : 0; }

  public static void startT_CLIENT_FANS_GET_OFFLINE_MESSAGE_RQ(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addSRqHead(FlatBufferBuilder builder, int sRqHeadOffset) { builder.addStruct(0, sRqHeadOffset, 0); }
  public static void addListOffcialOfflineMsgRequest(FlatBufferBuilder builder, int listOffcialOfflineMsgRequestOffset) { builder.addOffset(1, listOffcialOfflineMsgRequestOffset, 0); }
  public static int createListOffcialOfflineMsgRequestVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startListOffcialOfflineMsgRequestVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endT_CLIENT_FANS_GET_OFFLINE_MESSAGE_RQ(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
  public static void finishT_CLIENT_FANS_GET_OFFLINE_MESSAGE_RQBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
}

