// automatically generated by the FlatBuffers compiler, do not modify

package offcialpack;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class T_OFFCIAL_OFFLINE_MESSAGE extends Table {
  public static T_OFFCIAL_OFFLINE_MESSAGE getRootAsT_OFFCIAL_OFFLINE_MESSAGE(ByteBuffer _bb) { return getRootAsT_OFFCIAL_OFFLINE_MESSAGE(_bb, new T_OFFCIAL_OFFLINE_MESSAGE()); }
  public static T_OFFCIAL_OFFLINE_MESSAGE getRootAsT_OFFCIAL_OFFLINE_MESSAGE(ByteBuffer _bb, T_OFFCIAL_OFFLINE_MESSAGE obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public T_OFFCIAL_OFFLINE_MESSAGE __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public byte isFinish() { int o = __offset(4); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public long offcialId() { int o = __offset(6); return o != 0 ? bb.getLong(o + bb_pos) : 0; }
  public T_OFFLINE_MESSAGE sMsg(int j) { return sMsg(new T_OFFLINE_MESSAGE(), j); }
  public T_OFFLINE_MESSAGE sMsg(T_OFFLINE_MESSAGE obj, int j) { int o = __offset(8); return o != 0 ? obj.__init(__indirect(__vector(o) + j * 4), bb) : null; }
  public int sMsgLength() { int o = __offset(8); return o != 0 ? __vector_len(o) : 0; }

  public static int createT_OFFCIAL_OFFLINE_MESSAGE(FlatBufferBuilder builder,
      byte is_finish,
      long offcial_id,
      int s_msgOffset) {
    builder.startObject(3);
    T_OFFCIAL_OFFLINE_MESSAGE.addOffcialId(builder, offcial_id);
    T_OFFCIAL_OFFLINE_MESSAGE.addSMsg(builder, s_msgOffset);
    T_OFFCIAL_OFFLINE_MESSAGE.addIsFinish(builder, is_finish);
    return T_OFFCIAL_OFFLINE_MESSAGE.endT_OFFCIAL_OFFLINE_MESSAGE(builder);
  }

  public static void startT_OFFCIAL_OFFLINE_MESSAGE(FlatBufferBuilder builder) { builder.startObject(3); }
  public static void addIsFinish(FlatBufferBuilder builder, byte isFinish) { builder.addByte(0, isFinish, 0); }
  public static void addOffcialId(FlatBufferBuilder builder, long offcialId) { builder.addLong(1, offcialId, 0); }
  public static void addSMsg(FlatBufferBuilder builder, int sMsgOffset) { builder.addOffset(2, sMsgOffset, 0); }
  public static int createSMsgVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startSMsgVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endT_OFFCIAL_OFFLINE_MESSAGE(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
  public static void finishT_OFFCIAL_OFFLINE_MESSAGEBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
}

