// automatically generated by the FlatBuffers compiler, do not modify

package friendpack;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class T_CLINET_FRIEND_BLACKLIST_RS extends Table {
  public static T_CLINET_FRIEND_BLACKLIST_RS getRootAsT_CLINET_FRIEND_BLACKLIST_RS(ByteBuffer _bb) { return getRootAsT_CLINET_FRIEND_BLACKLIST_RS(_bb, new T_CLINET_FRIEND_BLACKLIST_RS()); }
  public static T_CLINET_FRIEND_BLACKLIST_RS getRootAsT_CLINET_FRIEND_BLACKLIST_RS(ByteBuffer _bb, T_CLINET_FRIEND_BLACKLIST_RS obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public T_CLINET_FRIEND_BLACKLIST_RS __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public commonpack.S_RS_HEAD sRsHead() { return sRsHead(new commonpack.S_RS_HEAD()); }
  public commonpack.S_RS_HEAD sRsHead(commonpack.S_RS_HEAD obj) { int o = __offset(4); return o != 0 ? obj.__init(o + bb_pos, bb) : null; }
  public long peerUserId() { int o = __offset(6); return o != 0 ? bb.getLong(o + bb_pos) : 0; }
  public int type() { int o = __offset(8); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public long token() { int o = __offset(10); return o != 0 ? bb.getLong(o + bb_pos) : 0; }

  public static void startT_CLINET_FRIEND_BLACKLIST_RS(FlatBufferBuilder builder) { builder.startObject(4); }
  public static void addSRsHead(FlatBufferBuilder builder, int sRsHeadOffset) { builder.addStruct(0, sRsHeadOffset, 0); }
  public static void addPeerUserId(FlatBufferBuilder builder, long peerUserId) { builder.addLong(1, peerUserId, 0); }
  public static void addType(FlatBufferBuilder builder, int type) { builder.addInt(2, type, 0); }
  public static void addToken(FlatBufferBuilder builder, long token) { builder.addLong(3, token, 0); }
  public static int endT_CLINET_FRIEND_BLACKLIST_RS(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
  public static void finishT_CLINET_FRIEND_BLACKLIST_RSBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
}

