// automatically generated by the FlatBuffers compiler, do not modify

package friendpack;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class T_SERVER_FRIEND_BLACKLIST_RQ extends Table {
  public static T_SERVER_FRIEND_BLACKLIST_RQ getRootAsT_SERVER_FRIEND_BLACKLIST_RQ(ByteBuffer _bb) { return getRootAsT_SERVER_FRIEND_BLACKLIST_RQ(_bb, new T_SERVER_FRIEND_BLACKLIST_RQ()); }
  public static T_SERVER_FRIEND_BLACKLIST_RQ getRootAsT_SERVER_FRIEND_BLACKLIST_RQ(ByteBuffer _bb, T_SERVER_FRIEND_BLACKLIST_RQ obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public T_SERVER_FRIEND_BLACKLIST_RQ __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public commonpack.S_RQ_HEAD sRqHead() { return sRqHead(new commonpack.S_RQ_HEAD()); }
  public commonpack.S_RQ_HEAD sRqHead(commonpack.S_RQ_HEAD obj) { int o = __offset(4); return o != 0 ? obj.__init(o + bb_pos, bb) : null; }
  public long peerUserId() { int o = __offset(6); return o != 0 ? bb.getLong(o + bb_pos) : 0; }
  public int type() { int o = __offset(8); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public long token() { int o = __offset(10); return o != 0 ? bb.getLong(o + bb_pos) : 0; }

  public static void startT_SERVER_FRIEND_BLACKLIST_RQ(FlatBufferBuilder builder) { builder.startObject(4); }
  public static void addSRqHead(FlatBufferBuilder builder, int sRqHeadOffset) { builder.addStruct(0, sRqHeadOffset, 0); }
  public static void addPeerUserId(FlatBufferBuilder builder, long peerUserId) { builder.addLong(1, peerUserId, 0); }
  public static void addType(FlatBufferBuilder builder, int type) { builder.addInt(2, type, 0); }
  public static void addToken(FlatBufferBuilder builder, long token) { builder.addLong(3, token, 0); }
  public static int endT_SERVER_FRIEND_BLACKLIST_RQ(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
  public static void finishT_SERVER_FRIEND_BLACKLIST_RQBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
}

