// automatically generated by the FlatBuffers compiler, do not modify

package grouppack;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class T_GROUP_CREATE_RQ extends Table {
  public static T_GROUP_CREATE_RQ getRootAsT_GROUP_CREATE_RQ(ByteBuffer _bb) { return getRootAsT_GROUP_CREATE_RQ(_bb, new T_GROUP_CREATE_RQ()); }
  public static T_GROUP_CREATE_RQ getRootAsT_GROUP_CREATE_RQ(ByteBuffer _bb, T_GROUP_CREATE_RQ obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public T_GROUP_CREATE_RQ __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public commonpack.S_RQ_HEAD sRqHead() { return sRqHead(new commonpack.S_RQ_HEAD()); }
  public commonpack.S_RQ_HEAD sRqHead(commonpack.S_RQ_HEAD obj) { int o = __offset(4); return o != 0 ? obj.__init(o + bb_pos, bb) : null; }
  public String groupName() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer groupNameAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public String groupImgUrl() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer groupImgUrlAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }
  public String groupRemark() { int o = __offset(10); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer groupRemarkAsByteBuffer() { return __vector_as_bytebuffer(10, 1); }
  public long groupCt() { int o = __offset(12); return o != 0 ? bb.getLong(o + bb_pos) : 0; }
  public int groupType() { int o = __offset(14); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public grouppack.T_OFFLINE_GROUP_MSG offlineGroupMsg() { return offlineGroupMsg(new grouppack.T_OFFLINE_GROUP_MSG()); }
  public grouppack.T_OFFLINE_GROUP_MSG offlineGroupMsg(grouppack.T_OFFLINE_GROUP_MSG obj) { int o = __offset(16); return o != 0 ? obj.__init(__indirect(o + bb_pos), bb) : null; }

  public static void startT_GROUP_CREATE_RQ(FlatBufferBuilder builder) { builder.startObject(7); }
  public static void addSRqHead(FlatBufferBuilder builder, int sRqHeadOffset) { builder.addStruct(0, sRqHeadOffset, 0); }
  public static void addGroupName(FlatBufferBuilder builder, int groupNameOffset) { builder.addOffset(1, groupNameOffset, 0); }
  public static void addGroupImgUrl(FlatBufferBuilder builder, int groupImgUrlOffset) { builder.addOffset(2, groupImgUrlOffset, 0); }
  public static void addGroupRemark(FlatBufferBuilder builder, int groupRemarkOffset) { builder.addOffset(3, groupRemarkOffset, 0); }
  public static void addGroupCt(FlatBufferBuilder builder, long groupCt) { builder.addLong(4, groupCt, 0); }
  public static void addGroupType(FlatBufferBuilder builder, int groupType) { builder.addInt(5, groupType, 0); }
  public static void addOfflineGroupMsg(FlatBufferBuilder builder, int offlineGroupMsgOffset) { builder.addOffset(6, offlineGroupMsgOffset, 0); }
  public static int endT_GROUP_CREATE_RQ(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
  public static void finishT_GROUP_CREATE_RQBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
}

