// automatically generated by the FlatBuffers compiler, do not modify

package grouppack;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class T_GROUP_CREATE_RS extends Table {
  public static T_GROUP_CREATE_RS getRootAsT_GROUP_CREATE_RS(ByteBuffer _bb) { return getRootAsT_GROUP_CREATE_RS(_bb, new T_GROUP_CREATE_RS()); }
  public static T_GROUP_CREATE_RS getRootAsT_GROUP_CREATE_RS(ByteBuffer _bb, T_GROUP_CREATE_RS obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public T_GROUP_CREATE_RS __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public commonpack.S_RS_HEAD sRsHead() { return sRsHead(new commonpack.S_RS_HEAD()); }
  public commonpack.S_RS_HEAD sRsHead(commonpack.S_RS_HEAD obj) { int o = __offset(4); return o != 0 ? obj.__init(o + bb_pos, bb) : null; }
  public grouppack.T_GROUP_BASE_INFO groupInfo() { return groupInfo(new grouppack.T_GROUP_BASE_INFO()); }
  public grouppack.T_GROUP_BASE_INFO groupInfo(grouppack.T_GROUP_BASE_INFO obj) { int o = __offset(6); return o != 0 ? obj.__init(__indirect(o + bb_pos), bb) : null; }
  public grouppack.T_OFFLINE_GROUP_MSG offlineGroupMsg() { return offlineGroupMsg(new grouppack.T_OFFLINE_GROUP_MSG()); }
  public grouppack.T_OFFLINE_GROUP_MSG offlineGroupMsg(grouppack.T_OFFLINE_GROUP_MSG obj) { int o = __offset(8); return o != 0 ? obj.__init(__indirect(o + bb_pos), bb) : null; }
  public int groupType() { int o = __offset(10); return o != 0 ? bb.getInt(o + bb_pos) : 0; }

  public static void startT_GROUP_CREATE_RS(FlatBufferBuilder builder) { builder.startObject(4); }
  public static void addSRsHead(FlatBufferBuilder builder, int sRsHeadOffset) { builder.addStruct(0, sRsHeadOffset, 0); }
  public static void addGroupInfo(FlatBufferBuilder builder, int groupInfoOffset) { builder.addOffset(1, groupInfoOffset, 0); }
  public static void addOfflineGroupMsg(FlatBufferBuilder builder, int offlineGroupMsgOffset) { builder.addOffset(2, offlineGroupMsgOffset, 0); }
  public static void addGroupType(FlatBufferBuilder builder, int groupType) { builder.addInt(3, groupType, 0); }
  public static int endT_GROUP_CREATE_RS(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
  public static void finishT_GROUP_CREATE_RSBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
}

