// automatically generated by the FlatBuffers compiler, do not modify

package grouppack;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class T_GROUP_RELATION_USER_INFO extends Table {
  public static T_GROUP_RELATION_USER_INFO getRootAsT_GROUP_RELATION_USER_INFO(ByteBuffer _bb) { return getRootAsT_GROUP_RELATION_USER_INFO(_bb, new T_GROUP_RELATION_USER_INFO()); }
  public static T_GROUP_RELATION_USER_INFO getRootAsT_GROUP_RELATION_USER_INFO(ByteBuffer _bb, T_GROUP_RELATION_USER_INFO obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public T_GROUP_RELATION_USER_INFO __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public long groupId() { int o = __offset(4); return o != 0 ? bb.getLong(o + bb_pos) : 0; }
  public byte messageStatus() { int o = __offset(6); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public byte saveType() { int o = __offset(8); return o != 0 ? bb.get(o + bb_pos) : 0; }

  public static int createT_GROUP_RELATION_USER_INFO(FlatBufferBuilder builder,
      long group_id,
      byte message_status,
      byte save_type) {
    builder.startObject(3);
    T_GROUP_RELATION_USER_INFO.addGroupId(builder, group_id);
    T_GROUP_RELATION_USER_INFO.addSaveType(builder, save_type);
    T_GROUP_RELATION_USER_INFO.addMessageStatus(builder, message_status);
    return T_GROUP_RELATION_USER_INFO.endT_GROUP_RELATION_USER_INFO(builder);
  }

  public static void startT_GROUP_RELATION_USER_INFO(FlatBufferBuilder builder) { builder.startObject(3); }
  public static void addGroupId(FlatBufferBuilder builder, long groupId) { builder.addLong(0, groupId, 0); }
  public static void addMessageStatus(FlatBufferBuilder builder, byte messageStatus) { builder.addByte(1, messageStatus, 0); }
  public static void addSaveType(FlatBufferBuilder builder, byte saveType) { builder.addByte(2, saveType, 0); }
  public static int endT_GROUP_RELATION_USER_INFO(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
  public static void finishT_GROUP_RELATION_USER_INFOBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
}

