// automatically generated by the FlatBuffers compiler, do not modify

package grouppack;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class T_GROUP_CLIENT_SEND_MESSAGE_RQ extends Table {
  public static T_GROUP_CLIENT_SEND_MESSAGE_RQ getRootAsT_GROUP_CLIENT_SEND_MESSAGE_RQ(ByteBuffer _bb) { return getRootAsT_GROUP_CLIENT_SEND_MESSAGE_RQ(_bb, new T_GROUP_CLIENT_SEND_MESSAGE_RQ()); }
  public static T_GROUP_CLIENT_SEND_MESSAGE_RQ getRootAsT_GROUP_CLIENT_SEND_MESSAGE_RQ(ByteBuffer _bb, T_GROUP_CLIENT_SEND_MESSAGE_RQ obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public T_GROUP_CLIENT_SEND_MESSAGE_RQ __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public commonpack.S_RQ_HEAD sRqHead() { return sRqHead(new commonpack.S_RQ_HEAD()); }
  public commonpack.S_RQ_HEAD sRqHead(commonpack.S_RQ_HEAD obj) { int o = __offset(4); return o != 0 ? obj.__init(o + bb_pos, bb) : null; }
  public long messageId() { int o = __offset(6); return o != 0 ? bb.getLong(o + bb_pos) : 0; }
  public long groupId() { int o = __offset(8); return o != 0 ? bb.getLong(o + bb_pos) : 0; }
  public commonpack.S_MSG sMsg() { return sMsg(new commonpack.S_MSG()); }
  public commonpack.S_MSG sMsg(commonpack.S_MSG obj) { int o = __offset(10); return o != 0 ? obj.__init(__indirect(o + bb_pos), bb) : null; }
  public String groupName() { int o = __offset(12); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer groupNameAsByteBuffer() { return __vector_as_bytebuffer(12, 1); }

  public static void startT_GROUP_CLIENT_SEND_MESSAGE_RQ(FlatBufferBuilder builder) { builder.startObject(5); }
  public static void addSRqHead(FlatBufferBuilder builder, int sRqHeadOffset) { builder.addStruct(0, sRqHeadOffset, 0); }
  public static void addMessageId(FlatBufferBuilder builder, long messageId) { builder.addLong(1, messageId, 0); }
  public static void addGroupId(FlatBufferBuilder builder, long groupId) { builder.addLong(2, groupId, 0); }
  public static void addSMsg(FlatBufferBuilder builder, int sMsgOffset) { builder.addOffset(3, sMsgOffset, 0); }
  public static void addGroupName(FlatBufferBuilder builder, int groupNameOffset) { builder.addOffset(4, groupNameOffset, 0); }
  public static int endT_GROUP_CLIENT_SEND_MESSAGE_RQ(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
  public static void finishT_GROUP_CLIENT_SEND_MESSAGE_RQBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
}

