// automatically generated by the FlatBuffers compiler, do not modify

package grouppack;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class T_GROUP_ALL_OFFLINE_MSG extends Table {
  public static T_GROUP_ALL_OFFLINE_MSG getRootAsT_GROUP_ALL_OFFLINE_MSG(ByteBuffer _bb) { return getRootAsT_GROUP_ALL_OFFLINE_MSG(_bb, new T_GROUP_ALL_OFFLINE_MSG()); }
  public static T_GROUP_ALL_OFFLINE_MSG getRootAsT_GROUP_ALL_OFFLINE_MSG(ByteBuffer _bb, T_GROUP_ALL_OFFLINE_MSG obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public T_GROUP_ALL_OFFLINE_MSG __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public byte isFinish() { int o = __offset(4); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public long groupId() { int o = __offset(6); return o != 0 ? bb.getLong(o + bb_pos) : 0; }
  public grouppack.T_OFFLINE_GROUP_MSG sOfflineMsgList(int j) { return sOfflineMsgList(new grouppack.T_OFFLINE_GROUP_MSG(), j); }
  public grouppack.T_OFFLINE_GROUP_MSG sOfflineMsgList(grouppack.T_OFFLINE_GROUP_MSG obj, int j) { int o = __offset(8); return o != 0 ? obj.__init(__indirect(__vector(o) + j * 4), bb) : null; }
  public int sOfflineMsgListLength() { int o = __offset(8); return o != 0 ? __vector_len(o) : 0; }

  public static int createT_GROUP_ALL_OFFLINE_MSG(FlatBufferBuilder builder,
      byte is_finish,
      long group_id,
      int s_offline_msg_listOffset) {
    builder.startObject(3);
    T_GROUP_ALL_OFFLINE_MSG.addGroupId(builder, group_id);
    T_GROUP_ALL_OFFLINE_MSG.addSOfflineMsgList(builder, s_offline_msg_listOffset);
    T_GROUP_ALL_OFFLINE_MSG.addIsFinish(builder, is_finish);
    return T_GROUP_ALL_OFFLINE_MSG.endT_GROUP_ALL_OFFLINE_MSG(builder);
  }

  public static void startT_GROUP_ALL_OFFLINE_MSG(FlatBufferBuilder builder) { builder.startObject(3); }
  public static void addIsFinish(FlatBufferBuilder builder, byte isFinish) { builder.addByte(0, isFinish, 0); }
  public static void addGroupId(FlatBufferBuilder builder, long groupId) { builder.addLong(1, groupId, 0); }
  public static void addSOfflineMsgList(FlatBufferBuilder builder, int sOfflineMsgListOffset) { builder.addOffset(2, sOfflineMsgListOffset, 0); }
  public static int createSOfflineMsgListVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startSOfflineMsgListVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endT_GROUP_ALL_OFFLINE_MSG(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
  public static void finishT_GROUP_ALL_OFFLINE_MSGBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
}

