// automatically generated by the FlatBuffers compiler, do not modify

package grouppack;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class T_GROUP_REMARK_DETAIL_RS extends Table {
  public static T_GROUP_REMARK_DETAIL_RS getRootAsT_GROUP_REMARK_DETAIL_RS(ByteBuffer _bb) { return getRootAsT_GROUP_REMARK_DETAIL_RS(_bb, new T_GROUP_REMARK_DETAIL_RS()); }
  public static T_GROUP_REMARK_DETAIL_RS getRootAsT_GROUP_REMARK_DETAIL_RS(ByteBuffer _bb, T_GROUP_REMARK_DETAIL_RS obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public T_GROUP_REMARK_DETAIL_RS __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public commonpack.S_RS_HEAD sRsHead() { return sRsHead(new commonpack.S_RS_HEAD()); }
  public commonpack.S_RS_HEAD sRsHead(commonpack.S_RS_HEAD obj) { int o = __offset(4); return o != 0 ? obj.__init(o + bb_pos, bb) : null; }
  public long groupId() { int o = __offset(6); return o != 0 ? bb.getLong(o + bb_pos) : 0; }
  public long opUserId() { int o = __offset(8); return o != 0 ? bb.getLong(o + bb_pos) : 0; }
  public long opCt() { int o = __offset(10); return o != 0 ? bb.getLong(o + bb_pos) : 0; }
  public String opRemark() { int o = __offset(12); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer opRemarkAsByteBuffer() { return __vector_as_bytebuffer(12, 1); }

  public static void startT_GROUP_REMARK_DETAIL_RS(FlatBufferBuilder builder) { builder.startObject(5); }
  public static void addSRsHead(FlatBufferBuilder builder, int sRsHeadOffset) { builder.addStruct(0, sRsHeadOffset, 0); }
  public static void addGroupId(FlatBufferBuilder builder, long groupId) { builder.addLong(1, groupId, 0); }
  public static void addOpUserId(FlatBufferBuilder builder, long opUserId) { builder.addLong(2, opUserId, 0); }
  public static void addOpCt(FlatBufferBuilder builder, long opCt) { builder.addLong(3, opCt, 0); }
  public static void addOpRemark(FlatBufferBuilder builder, int opRemarkOffset) { builder.addOffset(4, opRemarkOffset, 0); }
  public static int endT_GROUP_REMARK_DETAIL_RS(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
  public static void finishT_GROUP_REMARK_DETAIL_RSBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
}

