// automatically generated by the FlatBuffers compiler, do not modify

package grouppack;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class T_GROUP_DETAIL_INFO_RS extends Table {
  public static T_GROUP_DETAIL_INFO_RS getRootAsT_GROUP_DETAIL_INFO_RS(ByteBuffer _bb) { return getRootAsT_GROUP_DETAIL_INFO_RS(_bb, new T_GROUP_DETAIL_INFO_RS()); }
  public static T_GROUP_DETAIL_INFO_RS getRootAsT_GROUP_DETAIL_INFO_RS(ByteBuffer _bb, T_GROUP_DETAIL_INFO_RS obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public T_GROUP_DETAIL_INFO_RS __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public commonpack.S_RS_HEAD sRsHead() { return sRsHead(new commonpack.S_RS_HEAD()); }
  public commonpack.S_RS_HEAD sRsHead(commonpack.S_RS_HEAD obj) { int o = __offset(4); return o != 0 ? obj.__init(o + bb_pos, bb) : null; }
  public commonpack.USER_BASE_INFO listMembersInfo(int j) { return listMembersInfo(new commonpack.USER_BASE_INFO(), j); }
  public commonpack.USER_BASE_INFO listMembersInfo(commonpack.USER_BASE_INFO obj, int j) { int o = __offset(6); return o != 0 ? obj.__init(__indirect(__vector(o) + j * 4), bb) : null; }
  public int listMembersInfoLength() { int o = __offset(6); return o != 0 ? __vector_len(o) : 0; }
  public long groupId() { int o = __offset(8); return o != 0 ? bb.getLong(o + bb_pos) : 0; }
  public int groupMemberIndex() { int o = __offset(10); return o != 0 ? bb.getInt(o + bb_pos) : 0; }

  public static void startT_GROUP_DETAIL_INFO_RS(FlatBufferBuilder builder) { builder.startObject(4); }
  public static void addSRsHead(FlatBufferBuilder builder, int sRsHeadOffset) { builder.addStruct(0, sRsHeadOffset, 0); }
  public static void addListMembersInfo(FlatBufferBuilder builder, int listMembersInfoOffset) { builder.addOffset(1, listMembersInfoOffset, 0); }
  public static int createListMembersInfoVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startListMembersInfoVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addGroupId(FlatBufferBuilder builder, long groupId) { builder.addLong(2, groupId, 0); }
  public static void addGroupMemberIndex(FlatBufferBuilder builder, int groupMemberIndex) { builder.addInt(3, groupMemberIndex, 0); }
  public static int endT_GROUP_DETAIL_INFO_RS(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
  public static void finishT_GROUP_DETAIL_INFO_RSBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
}

