// automatically generated by the FlatBuffers compiler, do not modify

package grouppack;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class T_OPERATE_GROUP_MSG extends Table {
  public static T_OPERATE_GROUP_MSG getRootAsT_OPERATE_GROUP_MSG(ByteBuffer _bb) { return getRootAsT_OPERATE_GROUP_MSG(_bb, new T_OPERATE_GROUP_MSG()); }
  public static T_OPERATE_GROUP_MSG getRootAsT_OPERATE_GROUP_MSG(ByteBuffer _bb, T_OPERATE_GROUP_MSG obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public T_OPERATE_GROUP_MSG __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public long msgTime() { int o = __offset(4); return o != 0 ? bb.getLong(o + bb_pos) : 0; }
  public String operateUserName() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer operateUserNameAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public commonpack.USER_BASE_INFO userInfoList(int j) { return userInfoList(new commonpack.USER_BASE_INFO(), j); }
  public commonpack.USER_BASE_INFO userInfoList(commonpack.USER_BASE_INFO obj, int j) { int o = __offset(8); return o != 0 ? obj.__init(__indirect(__vector(o) + j * 4), bb) : null; }
  public int userInfoListLength() { int o = __offset(8); return o != 0 ? __vector_len(o) : 0; }
  public String groupModifyContent() { int o = __offset(10); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer groupModifyContentAsByteBuffer() { return __vector_as_bytebuffer(10, 1); }

  public static int createT_OPERATE_GROUP_MSG(FlatBufferBuilder builder,
      long msg_time,
      int operate_user_nameOffset,
      int user_info_listOffset,
      int group_modify_contentOffset) {
    builder.startObject(4);
    T_OPERATE_GROUP_MSG.addMsgTime(builder, msg_time);
    T_OPERATE_GROUP_MSG.addGroupModifyContent(builder, group_modify_contentOffset);
    T_OPERATE_GROUP_MSG.addUserInfoList(builder, user_info_listOffset);
    T_OPERATE_GROUP_MSG.addOperateUserName(builder, operate_user_nameOffset);
    return T_OPERATE_GROUP_MSG.endT_OPERATE_GROUP_MSG(builder);
  }

  public static void startT_OPERATE_GROUP_MSG(FlatBufferBuilder builder) { builder.startObject(4); }
  public static void addMsgTime(FlatBufferBuilder builder, long msgTime) { builder.addLong(0, msgTime, 0); }
  public static void addOperateUserName(FlatBufferBuilder builder, int operateUserNameOffset) { builder.addOffset(1, operateUserNameOffset, 0); }
  public static void addUserInfoList(FlatBufferBuilder builder, int userInfoListOffset) { builder.addOffset(2, userInfoListOffset, 0); }
  public static int createUserInfoListVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startUserInfoListVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addGroupModifyContent(FlatBufferBuilder builder, int groupModifyContentOffset) { builder.addOffset(3, groupModifyContentOffset, 0); }
  public static int endT_OPERATE_GROUP_MSG(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

