// automatically generated by the FlatBuffers compiler, do not modify

package commonpack;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class S_RS_HEAD extends Struct {
  public S_RS_HEAD __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public long userId() { return bb.getLong(bb_pos + 0); }
  public int packSessionId() { return bb.getInt(bb_pos + 8); }
  public int result() { return bb.getInt(bb_pos + 12); }
  public byte platform() { return bb.get(bb_pos + 16); }

  public static int createS_RS_HEAD(FlatBufferBuilder builder, long userId, int packSessionId, int result, byte platform) {
    builder.prep(8, 24);
    builder.pad(7);
    builder.putByte(platform);
    builder.putInt(result);
    builder.putInt(packSessionId);
    builder.putLong(userId);
    return builder.offset();
  }
}

