// automatically generated by the FlatBuffers compiler, do not modify

package commonpack;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class USER_BASE_INFO extends Table {
  public static USER_BASE_INFO getRootAsUSER_BASE_INFO(ByteBuffer _bb) { return getRootAsUSER_BASE_INFO(_bb, new USER_BASE_INFO()); }
  public static USER_BASE_INFO getRootAsUSER_BASE_INFO(ByteBuffer _bb, USER_BASE_INFO obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public USER_BASE_INFO __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public long userId() { int o = __offset(4); return o != 0 ? bb.getLong(o + bb_pos) : 0; }
  public String userNickName() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer userNickNameAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public int userGroupIndex() { int o = __offset(8); return o != 0 ? bb.getInt(o + bb_pos) : 0; }

  public static int createUSER_BASE_INFO(FlatBufferBuilder builder,
      long user_id,
      int user_nick_nameOffset,
      int user_group_index) {
    builder.startObject(3);
    USER_BASE_INFO.addUserId(builder, user_id);
    USER_BASE_INFO.addUserGroupIndex(builder, user_group_index);
    USER_BASE_INFO.addUserNickName(builder, user_nick_nameOffset);
    return USER_BASE_INFO.endUSER_BASE_INFO(builder);
  }

  public static void startUSER_BASE_INFO(FlatBufferBuilder builder) { builder.startObject(3); }
  public static void addUserId(FlatBufferBuilder builder, long userId) { builder.addLong(0, userId, 0); }
  public static void addUserNickName(FlatBufferBuilder builder, int userNickNameOffset) { builder.addOffset(1, userNickNameOffset, 0); }
  public static void addUserGroupIndex(FlatBufferBuilder builder, int userGroupIndex) { builder.addInt(2, userGroupIndex, 0); }
  public static int endUSER_BASE_INFO(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

