package com.qbao.newim.qbdb;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.qbao.newim.model.message.ScDBMessageModel;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "SC_DBMESSAGE_MODEL".
*/
public class ScDBMessageModelDao extends AbstractDao<ScDBMessageModel, Long> {

    public static final String TABLENAME = "SC_DBMESSAGE_MODEL";

    /**
     * Properties of entity ScDBMessageModel.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Message_id = new Property(0, long.class, "message_id", true, "_id");
        public final static Property Send_user_name = new Property(1, String.class, "send_user_name", false, "send_user_name");
        public final static Property Is_self = new Property(2, boolean.class, "is_self", false, "is_self");
        public final static Property B_id = new Property(3, long.class, "b_id", false, "b_id");
        public final static Property W_id = new Property(4, long.class, "w_id", false, "w_id");
        public final static Property C_id = new Property(5, long.class, "c_id", false, "c_id");
        public final static Property App_id = new Property(6, short.class, "app_id", false, "app_id");
        public final static Property Session_id = new Property(7, int.class, "session_id", false, "session_id");
        public final static Property Chat_type = new Property(8, short.class, "chat_type", false, "chat_type");
        public final static Property M_type = new Property(9, int.class, "m_type", false, "m_type");
        public final static Property S_type = new Property(10, int.class, "s_type", false, "s_type");
        public final static Property Ext_type = new Property(11, int.class, "ext_type", false, "ext_type");
        public final static Property Msg_content = new Property(12, String.class, "msg_content", false, "msg_content");
        public final static Property Msg_time = new Property(13, long.class, "msg_time", false, "msg_time");
        public final static Property Msg_status = new Property(14, short.class, "msg_status", false, "msg_status");
        public final static Property Audio_path = new Property(15, String.class, "audio_path", false, "audio_path");
        public final static Property Pic_path = new Property(16, String.class, "pic_path", false, "pic_path");
        public final static Property Compress_path = new Property(17, String.class, "compress_path", false, "compress_path");
        public final static Property Opt_user_id = new Property(18, long.class, "opt_user_id", false, "opt_user_id");
    }


    public ScDBMessageModelDao(DaoConfig config) {
        super(config);
    }
    
    public ScDBMessageModelDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"SC_DBMESSAGE_MODEL\" (" + //
                "\"_id\" INTEGER PRIMARY KEY NOT NULL ," + // 0: message_id
                "\"send_user_name\" TEXT," + // 1: send_user_name
                "\"is_self\" INTEGER NOT NULL ," + // 2: is_self
                "\"b_id\" INTEGER NOT NULL ," + // 3: b_id
                "\"w_id\" INTEGER NOT NULL ," + // 4: w_id
                "\"c_id\" INTEGER NOT NULL ," + // 5: c_id
                "\"app_id\" INTEGER NOT NULL ," + // 6: app_id
                "\"session_id\" INTEGER NOT NULL ," + // 7: session_id
                "\"chat_type\" INTEGER NOT NULL ," + // 8: chat_type
                "\"m_type\" INTEGER NOT NULL ," + // 9: m_type
                "\"s_type\" INTEGER NOT NULL ," + // 10: s_type
                "\"ext_type\" INTEGER NOT NULL ," + // 11: ext_type
                "\"msg_content\" TEXT," + // 12: msg_content
                "\"msg_time\" INTEGER NOT NULL ," + // 13: msg_time
                "\"msg_status\" INTEGER NOT NULL ," + // 14: msg_status
                "\"audio_path\" TEXT," + // 15: audio_path
                "\"pic_path\" TEXT," + // 16: pic_path
                "\"compress_path\" TEXT," + // 17: compress_path
                "\"opt_user_id\" INTEGER NOT NULL );"); // 18: opt_user_id
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"SC_DBMESSAGE_MODEL\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ScDBMessageModel entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getMessage_id());
 
        String send_user_name = entity.getSend_user_name();
        if (send_user_name != null) {
            stmt.bindString(2, send_user_name);
        }
        stmt.bindLong(3, entity.getIs_self() ? 1L: 0L);
        stmt.bindLong(4, entity.getB_id());
        stmt.bindLong(5, entity.getW_id());
        stmt.bindLong(6, entity.getC_id());
        stmt.bindLong(7, entity.getApp_id());
        stmt.bindLong(8, entity.getSession_id());
        stmt.bindLong(9, entity.getChat_type());
        stmt.bindLong(10, entity.getM_type());
        stmt.bindLong(11, entity.getS_type());
        stmt.bindLong(12, entity.getExt_type());
 
        String msg_content = entity.getMsg_content();
        if (msg_content != null) {
            stmt.bindString(13, msg_content);
        }
        stmt.bindLong(14, entity.getMsg_time());
        stmt.bindLong(15, entity.getMsg_status());
 
        String audio_path = entity.getAudio_path();
        if (audio_path != null) {
            stmt.bindString(16, audio_path);
        }
 
        String pic_path = entity.getPic_path();
        if (pic_path != null) {
            stmt.bindString(17, pic_path);
        }
 
        String compress_path = entity.getCompress_path();
        if (compress_path != null) {
            stmt.bindString(18, compress_path);
        }
        stmt.bindLong(19, entity.getOpt_user_id());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ScDBMessageModel entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getMessage_id());
 
        String send_user_name = entity.getSend_user_name();
        if (send_user_name != null) {
            stmt.bindString(2, send_user_name);
        }
        stmt.bindLong(3, entity.getIs_self() ? 1L: 0L);
        stmt.bindLong(4, entity.getB_id());
        stmt.bindLong(5, entity.getW_id());
        stmt.bindLong(6, entity.getC_id());
        stmt.bindLong(7, entity.getApp_id());
        stmt.bindLong(8, entity.getSession_id());
        stmt.bindLong(9, entity.getChat_type());
        stmt.bindLong(10, entity.getM_type());
        stmt.bindLong(11, entity.getS_type());
        stmt.bindLong(12, entity.getExt_type());
 
        String msg_content = entity.getMsg_content();
        if (msg_content != null) {
            stmt.bindString(13, msg_content);
        }
        stmt.bindLong(14, entity.getMsg_time());
        stmt.bindLong(15, entity.getMsg_status());
 
        String audio_path = entity.getAudio_path();
        if (audio_path != null) {
            stmt.bindString(16, audio_path);
        }
 
        String pic_path = entity.getPic_path();
        if (pic_path != null) {
            stmt.bindString(17, pic_path);
        }
 
        String compress_path = entity.getCompress_path();
        if (compress_path != null) {
            stmt.bindString(18, compress_path);
        }
        stmt.bindLong(19, entity.getOpt_user_id());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    @Override
    public ScDBMessageModel readEntity(Cursor cursor, int offset) {
        ScDBMessageModel entity = new ScDBMessageModel( //
            cursor.getLong(offset + 0), // message_id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // send_user_name
            cursor.getShort(offset + 2) != 0, // is_self
            cursor.getLong(offset + 3), // b_id
            cursor.getLong(offset + 4), // w_id
            cursor.getLong(offset + 5), // c_id
            cursor.getShort(offset + 6), // app_id
            cursor.getInt(offset + 7), // session_id
            cursor.getShort(offset + 8), // chat_type
            cursor.getInt(offset + 9), // m_type
            cursor.getInt(offset + 10), // s_type
            cursor.getInt(offset + 11), // ext_type
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // msg_content
            cursor.getLong(offset + 13), // msg_time
            cursor.getShort(offset + 14), // msg_status
            cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15), // audio_path
            cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16), // pic_path
            cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17), // compress_path
            cursor.getLong(offset + 18) // opt_user_id
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ScDBMessageModel entity, int offset) {
        entity.setMessage_id(cursor.getLong(offset + 0));
        entity.setSend_user_name(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setIs_self(cursor.getShort(offset + 2) != 0);
        entity.setB_id(cursor.getLong(offset + 3));
        entity.setW_id(cursor.getLong(offset + 4));
        entity.setC_id(cursor.getLong(offset + 5));
        entity.setApp_id(cursor.getShort(offset + 6));
        entity.setSession_id(cursor.getInt(offset + 7));
        entity.setChat_type(cursor.getShort(offset + 8));
        entity.setM_type(cursor.getInt(offset + 9));
        entity.setS_type(cursor.getInt(offset + 10));
        entity.setExt_type(cursor.getInt(offset + 11));
        entity.setMsg_content(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setMsg_time(cursor.getLong(offset + 13));
        entity.setMsg_status(cursor.getShort(offset + 14));
        entity.setAudio_path(cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15));
        entity.setPic_path(cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16));
        entity.setCompress_path(cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17));
        entity.setOpt_user_id(cursor.getLong(offset + 18));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(ScDBMessageModel entity, long rowId) {
        entity.setMessage_id(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(ScDBMessageModel entity) {
        if(entity != null) {
            return entity.getMessage_id();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(ScDBMessageModel entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
