// automatically generated by the FlatBuffers compiler, do not modify

package ecpack;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class T_EC_GETFREEWAITER_RQ extends Table {
  public static T_EC_GETFREEWAITER_RQ getRootAsT_EC_GETFREEWAITER_RQ(ByteBuffer _bb) { return getRootAsT_EC_GETFREEWAITER_RQ(_bb, new T_EC_GETFREEWAITER_RQ()); }
  public static T_EC_GETFREEWAITER_RQ getRootAsT_EC_GETFREEWAITER_RQ(ByteBuffer _bb, T_EC_GETFREEWAITER_RQ obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public T_EC_GETFREEWAITER_RQ __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public commonpack.S_RQ_HEAD sRqHead() { return sRqHead(new commonpack.S_RQ_HEAD()); }
  public commonpack.S_RQ_HEAD sRqHead(commonpack.S_RQ_HEAD obj) { int o = __offset(4); return o != 0 ? obj.__init(o + bb_pos, bb) : null; }
  public long bId() { int o = __offset(6); return o != 0 ? bb.getLong(o + bb_pos) : 0; }
  public long wIdList(int j) { int o = __offset(8); return o != 0 ? bb.getLong(__vector(o) + j * 8) : 0; }
  public int wIdListLength() { int o = __offset(8); return o != 0 ? __vector_len(o) : 0; }
  public ByteBuffer wIdListAsByteBuffer() { return __vector_as_bytebuffer(8, 8); }

  public static void startT_EC_GETFREEWAITER_RQ(FlatBufferBuilder builder) { builder.startObject(3); }
  public static void addSRqHead(FlatBufferBuilder builder, int sRqHeadOffset) { builder.addStruct(0, sRqHeadOffset, 0); }
  public static void addBId(FlatBufferBuilder builder, long bId) { builder.addLong(1, bId, 0); }
  public static void addWIdList(FlatBufferBuilder builder, int wIdListOffset) { builder.addOffset(2, wIdListOffset, 0); }
  public static int createWIdListVector(FlatBufferBuilder builder, long[] data) { builder.startVector(8, data.length, 8); for (int i = data.length - 1; i >= 0; i--) builder.addLong(data[i]); return builder.endVector(); }
  public static void startWIdListVector(FlatBufferBuilder builder, int numElems) { builder.startVector(8, numElems, 8); }
  public static int endT_EC_GETFREEWAITER_RQ(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
  public static void finishT_EC_GETFREEWAITER_RQBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
}

