// automatically generated by the FlatBuffers compiler, do not modify

package ecpack;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class T_EC_ISUSERBUSY_RS extends Table {
  public static T_EC_ISUSERBUSY_RS getRootAsT_EC_ISUSERBUSY_RS(ByteBuffer _bb) { return getRootAsT_EC_ISUSERBUSY_RS(_bb, new T_EC_ISUSERBUSY_RS()); }
  public static T_EC_ISUSERBUSY_RS getRootAsT_EC_ISUSERBUSY_RS(ByteBuffer _bb, T_EC_ISUSERBUSY_RS obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public T_EC_ISUSERBUSY_RS __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public commonpack.S_RS_HEAD sRsHead() { return sRsHead(new commonpack.S_RS_HEAD()); }
  public commonpack.S_RS_HEAD sRsHead(commonpack.S_RS_HEAD obj) { int o = __offset(4); return o != 0 ? obj.__init(o + bb_pos, bb) : null; }
  public long bId() { int o = __offset(6); return o != 0 ? bb.getLong(o + bb_pos) : 0; }
  public long cId() { int o = __offset(8); return o != 0 ? bb.getLong(o + bb_pos) : 0; }
  public int status() { int o = __offset(10); return o != 0 ? bb.getInt(o + bb_pos) : 0; }

  public static void startT_EC_ISUSERBUSY_RS(FlatBufferBuilder builder) { builder.startObject(4); }
  public static void addSRsHead(FlatBufferBuilder builder, int sRsHeadOffset) { builder.addStruct(0, sRsHeadOffset, 0); }
  public static void addBId(FlatBufferBuilder builder, long bId) { builder.addLong(1, bId, 0); }
  public static void addCId(FlatBufferBuilder builder, long cId) { builder.addLong(2, cId, 0); }
  public static void addStatus(FlatBufferBuilder builder, int status) { builder.addInt(3, status, 0); }
  public static int endT_EC_ISUSERBUSY_RS(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
  public static void finishT_EC_ISUSERBUSY_RSBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
}

