// automatically generated by the FlatBuffers compiler, do not modify

package ecpack;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class T_ECMSG_INFO extends Table {
  public static T_ECMSG_INFO getRootAsT_ECMSG_INFO(ByteBuffer _bb) { return getRootAsT_ECMSG_INFO(_bb, new T_ECMSG_INFO()); }
  public static T_ECMSG_INFO getRootAsT_ECMSG_INFO(ByteBuffer _bb, T_ECMSG_INFO obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public T_ECMSG_INFO __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public short appId() { int o = __offset(4); return o != 0 ? bb.getShort(o + bb_pos) : 0; }
  public int sessionId() { int o = __offset(6); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public short chatType() { int o = __offset(8); return o != 0 ? bb.getShort(o + bb_pos) : 0; }
  public int mType() { int o = __offset(10); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public int sType() { int o = __offset(12); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public int extType() { int o = __offset(14); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public long fromId() { int o = __offset(16); return o != 0 ? bb.getLong(o + bb_pos) : 0; }
  public long toId() { int o = __offset(18); return o != 0 ? bb.getLong(o + bb_pos) : 0; }
  public long bId() { int o = __offset(20); return o != 0 ? bb.getLong(o + bb_pos) : 0; }
  public long cId() { int o = __offset(22); return o != 0 ? bb.getLong(o + bb_pos) : 0; }
  public long wId() { int o = __offset(24); return o != 0 ? bb.getLong(o + bb_pos) : 0; }
  public long messageId() { int o = __offset(26); return o != 0 ? bb.getLong(o + bb_pos) : 0; }
  public long msgTime() { int o = __offset(28); return o != 0 ? bb.getLong(o + bb_pos) : 0; }
  public String msgContent() { int o = __offset(30); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer msgContentAsByteBuffer() { return __vector_as_bytebuffer(30, 1); }
  public String sendUserName() { int o = __offset(32); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer sendUserNameAsByteBuffer() { return __vector_as_bytebuffer(32, 1); }

  public static int createT_ECMSG_INFO(FlatBufferBuilder builder,
      short app_id,
      int session_id,
      short chat_type,
      int m_type,
      int s_type,
      int ext_type,
      long from_id,
      long to_id,
      long b_id,
      long c_id,
      long w_id,
      long message_id,
      long msg_time,
      int msg_contentOffset,
      int send_user_nameOffset) {
    builder.startObject(15);
    T_ECMSG_INFO.addMsgTime(builder, msg_time);
    T_ECMSG_INFO.addMessageId(builder, message_id);
    T_ECMSG_INFO.addWId(builder, w_id);
    T_ECMSG_INFO.addCId(builder, c_id);
    T_ECMSG_INFO.addBId(builder, b_id);
    T_ECMSG_INFO.addToId(builder, to_id);
    T_ECMSG_INFO.addFromId(builder, from_id);
    T_ECMSG_INFO.addSendUserName(builder, send_user_nameOffset);
    T_ECMSG_INFO.addMsgContent(builder, msg_contentOffset);
    T_ECMSG_INFO.addExtType(builder, ext_type);
    T_ECMSG_INFO.addSType(builder, s_type);
    T_ECMSG_INFO.addMType(builder, m_type);
    T_ECMSG_INFO.addSessionId(builder, session_id);
    T_ECMSG_INFO.addChatType(builder, chat_type);
    T_ECMSG_INFO.addAppId(builder, app_id);
    return T_ECMSG_INFO.endT_ECMSG_INFO(builder);
  }

  public static void startT_ECMSG_INFO(FlatBufferBuilder builder) { builder.startObject(15); }
  public static void addAppId(FlatBufferBuilder builder, short appId) { builder.addShort(0, appId, 0); }
  public static void addSessionId(FlatBufferBuilder builder, int sessionId) { builder.addInt(1, sessionId, 0); }
  public static void addChatType(FlatBufferBuilder builder, short chatType) { builder.addShort(2, chatType, 0); }
  public static void addMType(FlatBufferBuilder builder, int mType) { builder.addInt(3, mType, 0); }
  public static void addSType(FlatBufferBuilder builder, int sType) { builder.addInt(4, sType, 0); }
  public static void addExtType(FlatBufferBuilder builder, int extType) { builder.addInt(5, extType, 0); }
  public static void addFromId(FlatBufferBuilder builder, long fromId) { builder.addLong(6, fromId, 0); }
  public static void addToId(FlatBufferBuilder builder, long toId) { builder.addLong(7, toId, 0); }
  public static void addBId(FlatBufferBuilder builder, long bId) { builder.addLong(8, bId, 0); }
  public static void addCId(FlatBufferBuilder builder, long cId) { builder.addLong(9, cId, 0); }
  public static void addWId(FlatBufferBuilder builder, long wId) { builder.addLong(10, wId, 0); }
  public static void addMessageId(FlatBufferBuilder builder, long messageId) { builder.addLong(11, messageId, 0); }
  public static void addMsgTime(FlatBufferBuilder builder, long msgTime) { builder.addLong(12, msgTime, 0); }
  public static void addMsgContent(FlatBufferBuilder builder, int msgContentOffset) { builder.addOffset(13, msgContentOffset, 0); }
  public static void addSendUserName(FlatBufferBuilder builder, int sendUserNameOffset) { builder.addOffset(14, sendUserNameOffset, 0); }
  public static int endT_ECMSG_INFO(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
  public static void finishT_ECMSG_INFOBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
}

