// automatically generated by the FlatBuffers compiler, do not modify

package ecpack;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class T_EC_GETRECENTMSGS_RQ extends Table {
  public static T_EC_GETRECENTMSGS_RQ getRootAsT_EC_GETRECENTMSGS_RQ(ByteBuffer _bb) { return getRootAsT_EC_GETRECENTMSGS_RQ(_bb, new T_EC_GETRECENTMSGS_RQ()); }
  public static T_EC_GETRECENTMSGS_RQ getRootAsT_EC_GETRECENTMSGS_RQ(ByteBuffer _bb, T_EC_GETRECENTMSGS_RQ obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public T_EC_GETRECENTMSGS_RQ __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public commonpack.S_RQ_HEAD sRqHead() { return sRqHead(new commonpack.S_RQ_HEAD()); }
  public commonpack.S_RQ_HEAD sRqHead(commonpack.S_RQ_HEAD obj) { int o = __offset(4); return o != 0 ? obj.__init(o + bb_pos, bb) : null; }
  public long bId() { int o = __offset(6); return o != 0 ? bb.getLong(o + bb_pos) : 0; }
  public long cId() { int o = __offset(8); return o != 0 ? bb.getLong(o + bb_pos) : 0; }
  public long messageId() { int o = __offset(10); return o != 0 ? bb.getLong(o + bb_pos) : 0; }
  public int maxCnt() { int o = __offset(12); return o != 0 ? bb.getInt(o + bb_pos) : 0; }

  public static void startT_EC_GETRECENTMSGS_RQ(FlatBufferBuilder builder) { builder.startObject(5); }
  public static void addSRqHead(FlatBufferBuilder builder, int sRqHeadOffset) { builder.addStruct(0, sRqHeadOffset, 0); }
  public static void addBId(FlatBufferBuilder builder, long bId) { builder.addLong(1, bId, 0); }
  public static void addCId(FlatBufferBuilder builder, long cId) { builder.addLong(2, cId, 0); }
  public static void addMessageId(FlatBufferBuilder builder, long messageId) { builder.addLong(3, messageId, 0); }
  public static void addMaxCnt(FlatBufferBuilder builder, int maxCnt) { builder.addInt(4, maxCnt, 0); }
  public static int endT_EC_GETRECENTMSGS_RQ(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
  public static void finishT_EC_GETRECENTMSGS_RQBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
}

