// automatically generated by the FlatBuffers compiler, do not modify

package ecpack;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class T_GOODSINFTOIMS extends Table {
  public static T_GOODSINFTOIMS getRootAsT_GOODSINFTOIMS(ByteBuffer _bb) { return getRootAsT_GOODSINFTOIMS(_bb, new T_GOODSINFTOIMS()); }
  public static T_GOODSINFTOIMS getRootAsT_GOODSINFTOIMS(ByteBuffer _bb, T_GOODSINFTOIMS obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public T_GOODSINFTOIMS __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public long goodsId() { int o = __offset(4); return o != 0 ? bb.getLong(o + bb_pos) : 0; }
  public int goodsNum() { int o = __offset(6); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public long skuId() { int o = __offset(8); return o != 0 ? bb.getLong(o + bb_pos) : 0; }
  public int unitPrice() { int o = __offset(10); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public String goodsName() { int o = __offset(12); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer goodsNameAsByteBuffer() { return __vector_as_bytebuffer(12, 1); }
  public String skuText() { int o = __offset(14); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer skuTextAsByteBuffer() { return __vector_as_bytebuffer(14, 1); }
  public String imgUrl() { int o = __offset(16); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer imgUrlAsByteBuffer() { return __vector_as_bytebuffer(16, 1); }

  public static int createT_GOODSINFTOIMS(FlatBufferBuilder builder,
      long goodsId,
      int goodsNum,
      long skuId,
      int unitPrice,
      int goodsNameOffset,
      int skuTextOffset,
      int imgUrlOffset) {
    builder.startObject(7);
    T_GOODSINFTOIMS.addSkuId(builder, skuId);
    T_GOODSINFTOIMS.addGoodsId(builder, goodsId);
    T_GOODSINFTOIMS.addImgUrl(builder, imgUrlOffset);
    T_GOODSINFTOIMS.addSkuText(builder, skuTextOffset);
    T_GOODSINFTOIMS.addGoodsName(builder, goodsNameOffset);
    T_GOODSINFTOIMS.addUnitPrice(builder, unitPrice);
    T_GOODSINFTOIMS.addGoodsNum(builder, goodsNum);
    return T_GOODSINFTOIMS.endT_GOODSINFTOIMS(builder);
  }

  public static void startT_GOODSINFTOIMS(FlatBufferBuilder builder) { builder.startObject(7); }
  public static void addGoodsId(FlatBufferBuilder builder, long goodsId) { builder.addLong(0, goodsId, 0); }
  public static void addGoodsNum(FlatBufferBuilder builder, int goodsNum) { builder.addInt(1, goodsNum, 0); }
  public static void addSkuId(FlatBufferBuilder builder, long skuId) { builder.addLong(2, skuId, 0); }
  public static void addUnitPrice(FlatBufferBuilder builder, int unitPrice) { builder.addInt(3, unitPrice, 0); }
  public static void addGoodsName(FlatBufferBuilder builder, int goodsNameOffset) { builder.addOffset(4, goodsNameOffset, 0); }
  public static void addSkuText(FlatBufferBuilder builder, int skuTextOffset) { builder.addOffset(5, skuTextOffset, 0); }
  public static void addImgUrl(FlatBufferBuilder builder, int imgUrlOffset) { builder.addOffset(6, imgUrlOffset, 0); }
  public static int endT_GOODSINFTOIMS(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
  public static void finishT_GOODSINFTOIMSBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
}

